# Generated by Django 5.0.6 on 2024-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8)),
                ('lastName', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('dateOfRegister', models.DateField()),
            ],
            options={
                'ordering': ['lastName'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8)),
                ('lastName', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignedTo', models.CharField(max_length=8)),
                ('vehicleID', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateID', models.CharField(max_length=7)),
                ('brand', models.CharField(max_length=50)),
                ('brandModel', models.CharField(max_length=50)),
                ('ownerDNI', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['brand', 'brandModel'],
            },
        ),
    ]
