# Generated by Django 5.0.6 on 2024-06-28 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('asigned_to', models.CharField(max_length=8)),
                ('vehicle_ID', models.CharField(max_length=7)),
                ('description', models.CharField(default='', max_length=80)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_ID', models.CharField(max_length=7)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('brand_model', models.CharField(max_length=50)),
                ('owner_DNI', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['brand', 'brand_model'],
            },
        ),
    ]
