# Generated by Django 5.0.6 on 2024-07-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vehicle_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.vehicle', to_field='plate_ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_ID',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
