# Generated by Django 5.0.6 on 2024-07-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_vehicle_id_alter_vehicle_plate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='vehicle_ID',
            new_name='vehicle',
        ),
    ]
