# Generated by Django 5.0.6 on 2024-06-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(default='Auto', max_length=15),
            preserve_default=False,
        ),
    ]
