# Generated by Django 5.0.6 on 2024-06-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicle_vehicletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dateOfRegister',
        ),
    ]
