# Generated by Django 5.0.6 on 2024-07-08 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_vehicle_id_task_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DNI',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='asigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee', to_field='DNI'),
        ),
    ]
