# Generated by Django 5.0.6 on 2024-07-09 17:55

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='img',
            field=models.ImageField(upload_to=myapp.models.AvatarPath()),
        ),
    ]
