# Generated by Django 5.0.6 on 2024-07-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='DNI',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_DNI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='myapp.client', to_field='DNI'),
        ),
    ]
