# Generated by Django 5.0.6 on 2024-07-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_client_dni_alter_vehicle_owner_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Automóvil', 'Automovil'), ('Moto', 'Moto'), ('Camioneta', 'Camioneta'), ('SUV', 'SUV'), ('Camión', 'Camión'), ('Otro', 'Otro')], default='Automóvil', max_length=15),
        ),
    ]
